### ISSUE TITLE
ember data v2.12 and above is not supported

### ISSUE THREAD

**Issue by benjaminbalazs** [cardstack/ember-data-fastboot#10]
It seems that store.typeMaps has been removed from ember data starting from v2.12, for that reason the fastboot instance initializer fails to execute. I would have sent a PR, but I haven't found the solution how to get the data content of the store.

**Comment by kpfefferle** [comment]
@benjaminbalazs Is this the same issue being discussed in https://github.com/cardstack/ember-data-fastboot/pull/9?

**Comment by benjaminbalazs** [comment]
@kpfefferle Yes, sorry for raising this again.

**Comment by MartinMalinda** [comment]
Fixed by #9
