### ISSUE TITLE
calling createRecord in fastboot fails

### ISSUE THREAD

**Issue by arschmitz** [cardstack/ember-data-fastboot#8]
If in fastboot you call createRecord it will cause an error when the serialized data is pushed into the store in the browser. the record from the call to createRecord has no id and so by passing the serialized object to push you get the error 'Assertion Failed: you must pass an id for xxx when calling push'

**Comment by ef4** [comment]
Thanks for this bug report.

I think to fix this we will need to serialize the store itself at a lower level than we do now.

**Comment by krasnoukhov** [comment]
#13 seems to work just fine

**Comment by sarjanen** [comment]
Can we get this merged?

**Comment by ef4** [comment]
I merged and released #13 as 0.1.1.
